version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: be_the_hero_db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: be_the_hero_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - dev_data:/var/lib/mysql
      
volumes:
  dev_data: